test_name: Create weather for munich city via weather api

stages:
  - name: Create weather for munich city
    request:
      url: http://localhost:8080/weather
      method: POST
      headers:
        content-type: application/json
        authorization: Basic YWRtaW46YWRtaW4xMjM=
      json:
        date: "2023-03-14"
        lat: 123.1
        lon: 123.2
        city: Munich
        state: Germany
        temperatures: [ 21.8 ]
    response:
      status_code: 201


---

test_name: Fetch the weather when ID equals 1 via weather api

stages:
  - name: Fetch the weather when ID equals 1
    request:
      url: http://localhost:8080/weather/1
      method: GET
    response:
      status_code: 200
      json:
        id: 1
        date: "2023-03-14"
        lat: 123.1
        lon: 123.2
        city: Munich
        state: Germany
        temperatures: [ 21.8 ]

---

test_name: Fetch the weather for all available cities via weather api

stages:
  - name: Fetch the weather for all available cities
    request:
      url: http://localhost:8080/weather
      method: GET
      headers:
        authorization: Basic YWRtaW46YWRtaW4xMjM=
    response:
      status_code: 200

---
test_name: Fetch weather of an unknown city via weather api

stages:
  - name: Create weather for unknown city
    request:
      url: http://localhost:8080/weather/unknown
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 500

